name: rubenjanssens
favicon: null
layout_spectrum: 0.5986
typography_spectrum: 0.07117719552479684
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f1f3'
    - '#decdc1'
    - '#241f34'
    - '#95656a'
    - '#474835'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
